name: Karachi AQI Pipeline

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:     # Manual trigger

jobs:
  feature-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run feature pipeline
      env:
        AQICN_TOKEN: ${{ secrets.AQICN_TOKEN }}
        OPENWEATHER_TOKEN: ${{ secrets.OPENWEATHER_TOKEN }}
      run: |
        python run_demo.py
    
    - name: Commit and push if data changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add feature_store/
        git commit -m "Update feature store data [Automated]" || exit 0
        git push

  training-pipeline:
    runs-on: ubuntu-latest
    needs: feature-pipeline
    if: github.event_name == 'schedule'  # Run on schedule only
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run training pipeline
      run: |
        python src/model_training.py